config/routes.rb
Worshipschedule::Application.routes.draw do

  resources :teams do
    member do
      get :assign
      put :assign_all, :to => 'teams#assign_all'
      put :remove_all, :to => 'teams#remove_all'
      get :admins
      put :admins, :to => 'teams#update_admins'
      get :slots
    end
    
    resources :availabilities, :only => [:update, :create]
    
    resources :events do
      member do
        put :slots, :to => 'events#slots'
      end
    end
    resources :slots, :only => [:update]
    
    resources :memberships do
      member do
        get :skillships, :to => 'memberships#skillships'
        put :skillships, :to => 'memberships#update_skillships'
      end
    end
    
    resources :skills  do
      member do
        get :skillships, :to => 'skills#skillships'
        put :skillships, :to => 'skills#update_skillships'
      end
    end
  end

  resources :accounts do
    member do
      get :admins
      put :admins, :to => 'accounts#update_admins'
      put :owner
    end
  end
  
  resources :users do
    member do
      put :memberships_for
    end
  end
  
  match "users/:id/send_reset", :to => 'users#send_reset', :as => 'users/send_reset', :only => 'post'
  
  resource :profile, :only => [:edit, :update] do
    get :forgot
    post :send_reset
  end

  match "profile/reset/:token", :to => 'profiles#reset', :as => 'profile/reset'
  match "profile/update_reset/:id", :to => 'profiles#update_reset', :as => 'profile/update_reset', :only => 'post'
  
  resources :sessions, :only => [:new, :create, :destroy]
  get 'sessions/accounts'
  post 'sessions/set_account'
  
  match 'signin' => 'sessions#new'
  match 'signout' => 'sessions#destroy'

  get "pages/home"
  
  root :to => "pages#home"

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessor :validate_password
  
  attr_accessible :email, :first_name, :last_name, :home_phone, :mobile_phone, :office_phone, :office_phone_ext, :password, :password_confirmation
  
  default_scope :order => 'CASE WHEN (LENGTH(last_name) = 0) THEN LOWER(email) ELSE LOWER(last_name) END'
  
  has_many :accountships
  has_many :accounts, :through => :accountships
  has_many :memberships
  has_many :teams, :through => :memberships
  
  validates :first_name, :length => { :maximum => 50 }
  validates :last_name, :length => { :maximum => 50 }
  
  validates :password,
    :presence => true,
    :confirmation => true,
    :length => { :within => 4..50 },
    :if => :should_validate_password?
    
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true, :format => { :with => email_regex }
  
  phone_regex = /^[\(\)0-9\- \+\.]{10,20}$/
  validates_format_of :home_phone, :with => phone_regex, :allow_nil => true, :allow_blank => true
  validates_format_of :office_phone, :with => phone_regex, :allow_nil => true, :allow_blank => true
  validates_format_of :mobile_phone, :with => phone_regex, :allow_nil => true, :allow_blank => true

  before_save :encrypt_password
  
  def self.authenticate(email, submitted_password)
    user = find(:first, :conditions => [ "lower(email) = ?", email.downcase ])
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def name
    "#{self.first_name} #{self.last_name}"
  end
  
  def name_or_email
    unless self.first_name.blank?
      "#{self.first_name} #{self.last_name}"
    else
      self.email
    end
  end
  
  def first_name_or_email
    unless self.first_name.blank?
      self.first_name
    else
      self.email
    end
  end
  
  def sortable_name
    rv = self.email
    unless self.first_name.blank?
      rv = self.first_name
    end
    unless self.last_name.blank?
      rv = self.last_name
    end
    
    rv
  end
  
  def admin?(account)
    accountship = Accountship.where("user_id = ? AND account_id =?", self.id, account.id).first
    unless accountship.nil?
      accountship.admin?
    else
      false
    end
  end
  
  def owner?(account)
    account.owner_id == self.id
  end
  
  private
  
    def should_validate_password?
      if self.validate_password.nil?
        true
      else
        self.validate_password
      end
    end

    def encrypt_password
      self.salt = make_salt if self.new_record?
      self.encrypted_password = encrypt(self.password)
    end
    
    def encrypt(string)
      secure_hash("#{self.salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{self.password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    
    def clean_phone_numbers
      self.office_phone = self.office_phone.gsub(/[^0-9]/, '') unless self.office_phone.blank?
      self.home_phone = self.home_phone.gsub(/[^0-9]/, '') unless self.home_phone.blank?
      self.mobile_phone = self.mobile_phone.gsub(/[^0-9]/, '') unless self.mobile_phone.blank?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_account_admin, :except => [:show, :edit]
  before_filter(:except => [:new, :create, :index]) { require_user_for_current_account(params[:id]) }
  before_filter(:only => [:edit, :update]) { require_user_owned_by_current_user(params[:id]) }
  
  def create
    @user = User.new params[:user]
    @user.validate_password = false
    
    if @user.valid?
      
      existing_user = User.find(:first, :conditions => ["lower(email) = ?", @user.email.downcase])
      if existing_user.nil?
        @user.save
        @user.accounts << current_account
        
        reset_forgot_hash_for @user
        UserNotifier.welcome_new_user(@user, current_account, params[:msg], current_user).deliver
        flash[:success] = "#{@user.name_or_email} was added to your church! "
        redirect_to users_path
      else
        if existing_user.accounts(current_account).exists?
          flash[:error] = "That email address already belongs to a person with your church. "
          @title = 'All users'
          @sidebar_partial = 'users/sidebar/placeholder'
          render 'new'
        else
          existing_user.accounts << current_account
          
          UserNotifier.welcome_existing_user(@user, current_account, params[:msg], current_user).deliver
          flash[:success] = "#{existing_user.name_or_email} was added to your church! "
          redirect_to users_path
        end
      end

    else
      @title = "All people"
      @sidebar_partial = 'users/sidebar/placeholder'
      render 'new'
    end
  end
  
  def new
    @title = 'All people'
    @user = User.new
    @sidebar_partial = 'users/sidebar/placeholder'
  end
  
  def edit
    @user = User.find(params[:id])
    
    if @user == current_user
      @sidebar_partial = 'users/sidebar/placeholder'
      @title = "Your info"
    else
      @sidebar_partial = 'users/sidebar/edit_user'
      @title = "All people"
    end
    
    unless current_account.users.exists? @user
      flash[:error] = "You don't have permission to access that person. "
      redirect_to current_user
    end 
  end
  
  def update
    @user = User.find(params[:id])
    @user.validate_password = false
    
    if current_account.users.exists? @user
      if @user.update_attributes(params[:user])
        flash[:success] = "The settings for this person have been saved successfully. "
        redirect_to edit_user_path @user
      else
        if @user == current_user
          @title = "Your info"
        else
          @title = "All people"
        end
        @sidebar_partial = 'users/sidebar/placeholder'
        render 'edit'
      end
    else
      flash[:error] = "You don't have permission to access that person. "
      redirect_to current_user
    end
  end
  
  def index
    @users = current_account.users.all

    @title = 'All people'
    render :layout => 'full'
  end

  def show
    @teams = current_account.teams
    @user = User.find(params[:id])
    unless current_account.users.exists? @user
      flash[:error] = "You don't have permission to access that person. "
      redirect_to current_user
    end 

    @sidebar_partial = 'users/sidebar/placeholder'
    @title = 'Dashboard'
  end
  
  def destroy
    @user = User.find(params[:id])
    
    unless @user.id == current_user.id
      if current_account.users.exists? @user
        accountship = Accountship.where('user_id = ? AND account_id = ?', @user.id, current_account.id)
        Accountship.destroy accountship
        
        if @user.accounts.empty?
          User.destroy @user
        end
        
        flash[:success] = "#{@user.name_or_email} has been deleted. "
        redirect_to users_path
      else
        flash[:error] = "You don't have permission to access that person. "
        redirect_to current_user
      end
    else
      flash[:error] = "You are not allowed to remove your own account. "
      redirect_to edit_user_path(@user)
    end
  end
  
  def memberships_for
    @user = User.find(params[:id])
    @team_ids = Array.new(params[:team_id] || [])
    teams = current_account.teams
    
    teams.each do |team|
      if @team_ids.include?(team.id.to_s)
        Membership.set_to_active(team.id, @user.id)
      else
        Membership.set_to_inactive(team.id, @user.id)
      end
    end
    redirect_to edit_user_url(@user), :flash => { :success => "Team access for this person was changed" }
  end
    
  def send_reset
    @user = User.find(params[:id])
    reset_forgot_hash_with_timeout_for(@user)
    UserNotifier.forgot_password(@user).deliver
    flash[:success] = "This person has been emailed instructions to change their password. "
    redirect_to edit_user_url(@user)
  end
  
  private
  
    def require_user_owned_by_current_user(user_id)
      unless admin?
        user = User.find(user_id)
        
        user_team_ids = User.find(user_id).memberships.active.collect { |membership| membership.team_id }
        allowed_team_ids = User.find(current_user.id).memberships.admin.collect { |membership| membership.team_id }

        unless (user_team_ids & allowed_team_ids).any?
          redirect_to current_user, :flash => { :error => "You don't have permission for that person. "}
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50, :default => :identicon })
    gravatar_image_tag(
      user.email.downcase,
      :alt => user.name,
      :class => 'gravatar',
      :gravatar => options
    )
  end
  
  def link_for_new_team
    "<ul><li>#{link_to "New team", new_team_path, :class => 'cancel'}</li></ul>".html_safe
  end
end

app/views/users/_card.html.erb
<div class="card shadow">
  <div class="top">Your <%= APP_NAME %> profile</div>
  <div class="bottom">
    
    <table>
      <tbody>
        <tr>
          <td class="left"><%= gravatar_for user, :size => 50, :default => :identicon %></td>
          <td>
            <ul>
              <% unless user.name.blank? %>
                <li class="name"><%= user.name unless user.name.blank? %></li>
              <% end %>
              <li class="email"><%= truncate user.email, :length => 22 %></li>
              <li class="pass">Password: &bull;&bull;&bull;&bull;&bull;&bull;</li>
            </ul>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <div class="padlock"><%= image_tag "/images/icons/lock.png", :alt => "Secure" %></div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_fields.html.erb
  <%= render 'shared/errors', :object => f.object %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

app/views/users/_person.html.erb
<div class="thumbnail">
  <%= gravatar_for user %>
  <% user.accountships.each do |accountship| %>
    <% if accountship.account == current_account %>
      <% if user == current_account.owner %>
        <div class="owner">OWNER</div>
      <% elsif accountship.admin? %>
        <div class="admin">ADMIN</div>
      <% elsif ['memberships'].include?(controller.controller_name) %>
        <% if user.memberships.where(:team_id => params[:team_id]).first.admin %>
          <div class="team_admin">ADMIN</div>
        <% end %>
      <% else %>
        <div>&nbsp;</div>
      <% end %>
    <% end %>
  <% end %>
</div>

<ul>
  <% unless user.name.blank? %>
    <li><h4><%= user.name %></h4></li>
  <% end %>
  <li><%= link_to user.email, "#" %></li>
  <li><%= link_to 'Edit', edit_user_path(user), :class => 'cancel' %></li>
</ul>


app/views/users/edit.html.erb
<div class="content shadow">
  <div class="header">
    <% if @user == current_user %>
      <table class="edit_profile">
        <tbody>
          <tr>
            <td>
              <p><%= link_to 'Edit your personal information', edit_profile_path %></p>
              <p>Change the password or photo for your <%= APP_NAME %> account. </p>
            </td>
            <td>
              <%= render 'users/card', :user => current_user %>
            </td>
          </tr>
        </tbody>
      </table>
    <% else %>
      <h2>Edit <%= @user.name_or_email %></h2>
    <% end %>
  </div>
  
  <div class="form">
    <% if @user == current_user %>
      <h2 class="profile">Your contact information for this <%= APP_NAME %> account</h2>
    <% else %>
      <div class="recover_email">
        <h2>Need to find <%= @user.name_or_email.possessive %> password?</h2>
        <p>
          Each person's password is private to them, but you can email <%= @user.name_or_email %>
          <%= link_to 'instructions to choose a new password', users_send_reset_path(@user) %>.
        </p>
      </div
    <% end %>
    
    <%= form_for @user, :url => { :action => 'update' }  do |f| %>
      <%= render 'shared/errors', :object => f.object %>
      
      <% unless @user == current_user %>
        <div class="avatar">
          <%= gravatar_for @user, :size => 60, :default => :identicon %>
          <div>gravatar.com</div>
        </div>
      <% end %>
      <fieldset class="edit">
        <table>
          <tbody>
            <% if @user == current_user %>
              <tr>
                <td><%= f.label :first_name, 'First name' %></td>
                <td><%= f.text_field :first_name %>
              </tr>
              <tr>
                <td><%= f.label :last_name, 'Last name' %></td>
                <td><%= f.text_field :last_name %>
              </tr>
              <tr>
                <td><%= f.label :email, 'Email' %></td>
                <td><%= f.text_field :email %>
              </tr>
            <% else %>
              <tr class="read_only">
                <td>Name</td>
                <td>
                  <% if @user.name.blank? %>
                    (not provided)
                  <% else %>
                    <%= @user.name %>
                  <% end %>
                </td>
              </tr>
              <tr class="read_only">
                <td>Email</td>
                <td><%= @user.email %></td>
              </tr>
            <% end %>
            <tr>
              <td><%= f.label :office_phone, 'Office #' %></td>
              <td>
                <%= f.text_field :office_phone %>
                <%= f.label :office_phone_ext, 'ext'%>
                <%= f.text_field :office_phone_ext, :class => 'ext'%>
              </td>
            </tr>
            <tr>
              <td><%= f.label :home_phone, 'Home #' %></td>
              <td><%= f.text_field :home_phone %></td>
            </tr>
            <tr>
              <td><%= f.label :mobile_phone, 'Mobile #' %></td>
              <td><%= f.text_field :mobile_phone %></td>
            </tr>
          </tbody>
        </table>
      </fieldset>
    
      <div class="footer">
        <% if @user == current_user %>
          <%= f.submit 'Save changes' %>
        <% else %>
          <%= f.submit 'Save this person' %>
        <% end %>
        or <%= link_to 'Cancel', users_path, :class => "cancel" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="content shadow">
  <div class="header">
    <%= render :partial => 'shared/button_link', :locals => {:url => new_user_path, :text => 'Add a new person' } %>
    <h1>Every person from your church</h1>
  </div>
  
  <table class="persons">
    
    <thead>
      <tr>
        <th colspan="3" class="big">
          <strong>Your church:</strong> <%= current_account.name %>
          <span class="link">See the <%= link_to 'administrator list', admins_account_path(current_account), :class => 'cancel' %> to give or take away admin powers</span>
        </th>
      </tr>
    </thead>
  
    <tbody>
      <% @users.each_slice(3) do |row| %>
        <tr>
          <% row.each do |user| %>
            <td>
              <%= render 'person', :user => user %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
    
  </table>
</div>


app/views/users/new.html.erb
<div class="content shadow">
  <div class="header">
    <h2>Add a person to <%= current_account.name %></h2>
  </div>
  
  <div class="form">
    <%= form_for @user, :url => { :action => 'create' } do |f| %>
      <%= render 'shared/errors', :object => f.object %>
      <div class="fieldset_desc">
        This person's name will appear next to their events on your schedules.
        If you don't provide a name, <%= APP_NAME %> will use their email address instead. 
      </div>
      <fieldset>
        <table>
          <tbody>
            <tr>
              <th><%= f.label :email %></th>
              <td><%= f.text_field :email %></td>
            </tr>
            <tr>
              <td><%= f.label :first_name %></td>
              <td><%= f.text_field :first_name %></td>
            </tr>
            <tr>
              <td><%= f.label :last_name %></td>
              <td><%= f.text_field :last_name %></td>
            </tr>
          </tbody>
        </table>
      </fieldset>
      
      <div class="fieldset_desc">
        The rest is optional.
        You can fill it in later if you would like. 
      </div>
      <fieldset>
        <table>
          <tbody>
            <tr>
              <td><%= f.label :office_phone, 'Office #' %></td>
              <td>
                <%= f.text_field :office_phone %>
                <%= f.label :office_phone_ext, 'ext'%>
                <%= f.text_field :office_phone_ext, :class => 'ext'%>
              </td>
            </tr>
            <tr>
              <td><%= f.label :home_phone, 'Home #' %></td>
              <td><%= f.text_field :home_phone %></td>
            </tr>
            <tr>
              <td><%= f.label :mobile_phone, 'Mobile #' %></td>
              <td><%= f.text_field :mobile_phone %></td>
            </tr>
          </tbody>
        </table>
      </fieldset>
      
      <div class="fieldset_desc">
      <h2>Include a personal note along with the invitation to set up their account?</h2>
        This person will receive a welcome email with a link to set their own password.
        You can also add a personalized note that will appear at the bottom of the email.
        Please use plain text
        (no HTML tags).
      </div>
      <fieldset class="note">
        <%= text_area_tag :msg, nil, :rows => 7, :columns => 60 %>
      </fieldset>
      
      <div class="footer">
        <h2>What happens now?</h2>
        <p>
          When you click the "Add this person" button below,
          we'll fire off an invitation to the email address you entered above.
          The email will contain a link to a web page where this person can complete the setup process
          by picking their own password.
          Plus, you can immediately start involving them on your <%= APP_NAME %> teams or placing them on schedules
          even before they've completed their account setup. 
        </p>
        <%= f.submit 'Add this person' %>
        or <%= link_to "Cancel", users_path, :class => "cancel" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="header big">
  <h1>Update your <%= APP_NAME %> profile details</h1>
</div>

<%= form_for @user, :url => { :action => 'update_profile'}  do |f| %>
  <%= render 'shared/errors', :object => f.object %>

  <fieldset class="edit profile">
    <table>
      <tbody>
        <tr>
          <td><%= f.label :password %></td>
          <td>
            <%= f.password_field :password %>
          </td>
        </tr>
        <tr class="hint">
          <td>&nbsp;</td>
          <td>
            <div>4 characters or longer. Add at least one number for extra safety. </div>
          </td>
        </tr>
        <tr>
          <td><%= f.label :password_confirmation, 'Confirm<br />password'.html_safe %></td>
          <td>
            <%= f.password_field :password_confirmation %>
          </td>
        </tr>
      </tbody>
    </table>
  </fieldset>
  <div class="action">
    <%= f.submit 'Change password' %>
    or <%= link_to 'Cancel', edit_user_path(current_user), :class => 'cancel' %>
  </div>
<% end %>

<fieldset class="edit_gravatar">
  <%= gravatar_for current_user, :size => 70, :default => :identicon %>
  <h3>Your gravatar image</h3>
  <p>
    Your profile image is provided by the free Gravatar service, which generates a unique avatar image for you from your email address.
    Replace it with your own custom image by visiting gravatar.com.
  </p>
  <p><%= link_to 'Change my Gravatar image', "http://en.gravatar.com/", :target => '_blank' %></p>
</fieldset>

app/views/users/show.html.erb
<div class="content shadow">
  <div class="header">
    <%= link_for_new_team if admin?%>
    <h2>Latest activity for your teams</h2>
  </div>
  <div class="dashboard">
    
    <% @teams.each do |team| %>
      <h1>Your team: <%= link_to team.name, team_path(team) %></h1>
      <table>
        <thead>
          <tr>
            <th colspan="4"><a href="#"><%=current_account.name %> &mdash; <span><%= team.name %></span></a></th>
        </thead>
        <tbody>
          <tr>
            <td class="what"><span class='availability'>Availability</span></td>
            <td><a href="#">New events added</a></td>
            <td class="who">posted by <span>Jim D</span></td>
            <td class="last">May 2</td>
          </tr>
          <tr>
            <td class="what"><span class='church'>Apr 28</span></td>
            <td><%= link_to 'Sunday worship', root_path %></td>
            <td class="who">posted by <span>Jim D</span></td>
            <td class="last">&nbsp;</td>
          </tr>
          <tr>
            <td class="what"><span class='church'>Apr 29</span></td>
            <td><%= link_to 'Saturday worship', root_path %></td>
            <td class="who">posted by <span>Jim D</span></td>
            <td class="last">&nbsp;</td>
          </tr>
          <tr>
            <td class="what"><span class='church'>May 7</span></td>
            <td><%= link_to 'Ignite!', root_path %></td>
            <td class="who">posted by <span>Jim D</span></td>
            <td class="last">&nbsp;</td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </div>
</div>