config/routes.rb
Worshipschedule::Application.routes.draw do

  resources :teams do
    member do
      get :assign
      put :assign_all, :to => 'teams#assign_all'
      put :remove_all, :to => 'teams#remove_all'
      get :admins
      put :admins, :to => 'teams#update_admins'
      get :slots
    end
    
    resources :availabilities, :only => [:update, :create]
    
    resources :events do
      member do
        put :slots, :to => 'events#slots'
      end
    end
    resources :slots, :only => [:update]
    
    resources :memberships do
      member do
        get :skillships, :to => 'memberships#skillships'
        put :skillships, :to => 'memberships#update_skillships'
      end
    end
    
    resources :skills  do
      member do
        get :skillships, :to => 'skills#skillships'
        put :skillships, :to => 'skills#update_skillships'
      end
    end
  end

  resources :accounts do
    member do
      get :admins
      put :admins, :to => 'accounts#update_admins'
      put :owner
    end
  end
  
  resources :users do
    member do
      put :memberships_for
    end
  end
  
  match "users/:id/send_reset", :to => 'users#send_reset', :as => 'users/send_reset', :only => 'post'
  
  resource :profile, :only => [:edit, :update] do
    get :forgot
    post :send_reset
  end

  match "profile/reset/:token", :to => 'profiles#reset', :as => 'profile/reset'
  match "profile/update_reset/:id", :to => 'profiles#update_reset', :as => 'profile/update_reset', :only => 'post'
  
  resources :sessions, :only => [:new, :create, :destroy]
  get 'sessions/accounts'
  post 'sessions/set_account'
  
  match 'signin' => 'sessions#new'
  match 'signout' => 'sessions#destroy'

  get "pages/home"
  
  root :to => "pages#home"

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :name, :description
  
  default_scope :order => :name
  belongs_to :team
  
  has_many :skillships, :dependent => :destroy
  has_many :memberships, :through => :skillships
    
  validates :team_id, :presence => true, :length => { :minimum => 1 }
  validates :name, :presence => true, :length => { :maximum => 100 }
  validates :description, :length => { :maximum => 500 } 
  
  def assign_skillships(membership_ids)
    skillships = self.skillships.find(:all)
    
    # remove the skillships missing from the passed in list ..
    skillships.each do |skillship|
      unless membership_ids.include?(skillship.membership_id.to_s)
        skillship.delete
      end
    end
    
    # add the skillships that don't already exist ..
    membership_ids.each do |id|
      if self.skillships.find_by_membership_id(id).nil?
        self.skillships.create(:membership_id => id)
      end
    end
  end 
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :account
  
  default_scope :order => 'name ASC'
  
  has_many :memberships, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :skills, :dependent => :destroy
  
  validates_presence_of :account_id
  validates_presence_of :name
  
  def new_availability_for?(user)
    membership = self.memberships.find_by_user_id(user.id)    
    
    if membership.nil?
      # this user is not on this team
      false
    elsif self.events == membership.events
      # there is an availability row for each event
      false
    else
      true
    end
  end
  
  def assign_administrators(ids, current_user)
    memberships = self.memberships.find(:all, :include => :user)
    
    memberships.each do |membership|
      
      # don't modify current_user, owner, or account admins
      if ids.include?(membership.id.to_s)
        membership.update_attribute(:admin, true) unless membership.admin?
      else
        membership.update_attribute(:admin, false) if membership.admin?
      end
    end
  end
  
  def self.add_all_account_users(account, team)
    team.users = account.users
    Membership.update_all({ :active => true }, { :team_id => team.id })
  end
  
  def self.remove_all_account_users(team)
    Membership.update_all({ :active => false }, { :team_id => team.id })
  end
  
  def self.member?(user)
    self.users.exists?(user)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_filter(:except => [:index, :show]) { require_account_or_team_admin(params[:team_id]) }
  before_filter { require_team_for_current_account(params[:team_id]) }
  before_filter(:only => [:destroy, :edit, :update, :show, :skillships, :update_skillships]) { require_skill_for_current_team(params[:team_id], params[:id]) }
  before_filter(:only => [:update_skillships]) { require_memberships_for_current_team(params[:team_id], params[:membership_ids] || []) }
  before_filter { require_team_member(params[:team_id]) }
  
  def update_skillships
    @team = Team.find(params[:team_id])
    @skill = Skill.find(params[:id])
    
    @skill.assign_skillships(params[:membership_ids] || [])
    flash[:success] = "The members with this skill were changed"
    redirect_to edit_team_skill_url(@team, @skill)
  end
  
  def skillships
    @team = Team.find(params[:team_id])
    @skill = Skill.find(params[:id])
    @sidebar_partial = 'users/sidebar/placeholder'
    @title = "Assign skill"
    @memberships = @team.memberships.joins(:user).where(:active => true).order('CASE WHEN (LENGTH(last_name) = 0) THEN LOWER(email) ELSE LOWER(last_name) END')
  end
  
  def show
    @team = Team.find(params[:team_id])
    @skill = Skill.find(params[:id])
    @skillships = Skillship.joins(:membership).where("skillships.skill_id = ? AND memberships.active = ?", @skill.id, true)
    @skillships.sort! { |a,b,| a.membership.user.sortable_name.downcase <=> b.membership.user.sortable_name.downcase }
    @sidebar_partial = 'skills/sidebar/show'
    @title = "Skill details"
  end
  
  def update
    @team = Team.find(params[:team_id])
    @skill = Skill.find(params[:id])
    if @skill.update_attributes(params[:skill])
      flash[:success] = "The changes to the skill were saved"     
      redirect_to team_skills_url(@team)
    else
      @sidebar_partial = 'skills/sidebar/show'
      render 'edit'
    end
  end
  
  def edit
    @team = Team.find(params[:team_id])
    @skill = Skill.find(params[:id])
    @skillships = Skillship.joins(:membership).where("skillships.skill_id = ? AND memberships.active = ?", @skill.id, true)
    @skillships.sort! { |a,b,| a.membership.user.sortable_name.downcase <=> b.membership.user.sortable_name.downcase }
    @sidebar_partial = 'skills/sidebar/edit'
    @title = 'Skill settings'
    
    render 'edit'
  end
  
  def destroy 
    @skill = Skill.find(params[:id])
    @skill.delete
    
    redirect_to team_skills_url(@team), :flash => { :success => "The skill was removed from this team" }
  end
  
  def index
    @team = Team.find(params[:team_id])
    @skills = @team.skills
    membership = Membership.where('user_id = ? AND team_id = ? and active = ?', current_user.id, @team.id, true).first
    @skillships = Skillship.where('membership_id = ?', membership.id).all unless membership.nil?
    @sidebar_partial = 'skills/sidebar/index'
    @title = 'Team skills'
    render 'index'
  end
  
  def create
    @team = Team.find(params[:team_id])
    @skill = @team.skills.new(params[:skill])
    if @skill.save
      flash[:success] = 'The new skill was successfully saved'
      redirect_to team_skills_url(@team)
    else
      @sidebar_partial = 'users/sidebar/placeholder'
      @title = 'New skill'
      render 'new'
    end
  end
  
  def new
    @team = Team.find(params[:team_id])
    @skill = @team.skills.build
    @title = 'New skill'
    @sidebar_partial = 'users/sidebar/placeholder'
  end
  
  private
  
    def require_skill_for_current_team(team_id, skill_id)
      skill = Skill.find(skill_id)
      current_team = Team.find(team_id)
      unless current_team.skills.exists?(skill)
        redirect_to current_user, :flash => { :error => "You don't have permission to modify that skill" }
      end      
    end
end

app/views/skills/_fields.html.erb
<h3>Skill name</h3>
<p class="block_intro">Skills are what your team members will do when they are scheduled for an event. </p>
<div class="block">
  <%= f.text_field :name %>
</div>
<h3>Description</h3>
<p class="block_intro">Provide an optional description. </p>
<div class="block">
  <%= f.text_area :description, :cols => 50, :rows => 10 %>
</div>

app/views/skills/edit.html.erb
<div class="content shadow">
  <div class="header">
    <h2>Edit skill for <%= @team.name %></h2>
  </div>
  <div class="form">
    <%= form_for @skill, :url => { :action => 'update' } do |f| %>
      <%= render 'shared/errors', :object => @skill %>
      <%= render 'fields', :f => f %>      
      <div class="footer">
        <%= f.submit "Save changes" %>
        or <%= link_to "Cancel", team_skills_path(@team), :class => 'cancel' %>
      </div>
    <% end %>
  </div>
</div>

app/views/skills/index.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    
    $(document).ready(function(){
			$("tr, .hover_menu").hover(
				function(){
					$(this).children("td").children(".hover_menu").show()
				},
				function(){
					$(this).children("td").children(".hover_menu").hide()
				}
			)
    })
  </script>
<% end %>

<div class="content shadow">
  <div class="header">
	<% if admin? || team_admin?(@team, current_user) %>
		<div class="link_bar">
			<%= link_to 'New skill', new_team_skill_path(@team) %>
		</div>
	<% end %>
    <h2>All skills for <%= @team.name %></h2>
  </div>
		
	<% if @team.skills.any? %>
		<div class="listing">
			<table>
				<% @team.skills.each do |skill| %>
					<tr>
						<td class="what">
							<span class="skill">Skill</span>
						</td>
						<td class="item">
							<% if team_admin?(@team, current_user)%>
								<div class="hover_menu">
							    <%= link_to "Edit", edit_team_skill_path(@team, skill), :class => 'cancel' %>
								</div>
							<% end %>
							<div><%= link_to skill.name, team_skill_path(@team, skill) %></div>
							<% unless skill.description.nil? %>
								<div class="desc"><%= skill.description %>
							<% end %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	<% else %>
		<div class="blank_slate">
	    <%= image_tag 'empty_box.png', :style => 'width:125px;' %>
			<div class="message">
				<% if team_admin?(@team, current_user) %>
					<h2>Let's add the first skill to this team! </h2>
					<p>
						Skills are things your team members can do. 
						They help you decide who to schedule for events.
					</p>
	      	<%= render :partial => 'shared/button_link', :locals => { :url => new_team_skill_path(@team), :text => 'Add the first skill' } %>				
				<% elsif %>
					<h2>No skills have been assigned to you yet! </h2>
					<p>
						Skills are things you can do for this team. 
						A team administrator still needs to add skills to your profile for this team. 
					</p>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/skills/new.html.erb
<div class="content shadow">
  <div class="header">
    <h2>New skill for <%= @team.name %></h2>
  </div>
  <div class="form">
    <%= form_for @skill, :url => { :action => 'create' } do |f| %>
      <%= render 'shared/errors', :object => @skill %>
      <%= render 'fields', :f => f %>      
      <div class="footer">
        <%= f.submit "Save changes" %>
        or <%= link_to "Cancel", team_skills_path(@team), :class => 'cancel' %>
      </div>
    <% end %>
  </div>
</div>

app/views/skills/show.html.erb
<div class="content shadow">
  <div class="header">
		<% if admin? || team_admin?(@team, current_user) %>
			<div class="link_bar">
				<%= link_to 'New skill', new_team_skill_path(@team) %>
				|
				<%= link_to 'Edit', edit_team_skill_path(@team, @skill) %>
			</div>
		<% end %>
		<%= link_to "&laquo; All skills".html_safe, team_skills_path(@team), :class => 'back_link' %>
  </div>
	<div class="listing">
		<h3><%= @skill.name %></h3>
		<p>
		<% if @skill.description.blank? %>
			No description provided
		<% else %>
			<%= @skill.description %>
		<% end %>
		</p>
	</div>
</div>	

app/views/skills/skillships.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    
    $(document).ready(function(){
			var dirty = false
      
      $(".bulk_links a").click(function(){
				var action = $(this).attr('data-action')
				
				if (action == 'update-all') {
					$(".checkbox").attr("checked", true)
				}
				else {
					$(".checkbox").attr("checked", false)
					dirty = true
				}
				return false
      })

			$(".checkbox").change(function(){
				if ($(this).attr("checked") == "") {dirty = true}
			})
			
			$(".submit").click(function(){
				var answer 
				if (dirty) {
					answer = confirm($(this).attr("data-message"))
					if (!answer) {
						return false
					}
				}
			})
    })
  </script>
<% end %>

<div class="content shadow">
  <div class="header">
    <h1>Assign this skill to team members</h1>
  </div>
	<% if @memberships.any? %>
	  <div class="form assign">
	    <%= form_tag skillships_team_skill_path(@team, @skill), :method => :put do %>
		    <div class="action">
					<%= submit_tag 'Save these changes', :class => 'submit', 'data-message' => 'Are you sure? If you are removing this skill from any members, they will be removed from events where they are scheduled for this skill. There is no undo. ' %>
		      <%= link_to "&laquo;  Cancel".html_safe, edit_team_skill_path(@team, @skill) %>
		      <p>
		        <span>Assign skills</span>
						Check the box in front of someone's name to assign this skill to them. 
						Uncheck to remove the skill.
						<br /><br />
						If a member is checked here, you will be able to schedule them for '<%= @skill.name %>' when you create an event.
		      </p>
		    </div>
		    <table>
		      <thead>
		        <tr>
		          <th><%= @skill.name %></th>
		        </tr>
		      </thead>
		      <tbody>
		        <tr>
		          <td class="bulk_links">
		            Assign skill to:
		            <%= link_to 'Everyone', '#', 'data-action' => 'update-all' %>
		            | <%= link_to 'No one', '#', 'data-action' => 'clear-all' %>
		          </td>
		        </tr>          
		        <% @memberships.each do |membership| %>
		          <tr>
		            <td>
			            <label>
			              <%= check_box_tag "membership_ids[]", membership.id, @skill.memberships.include?(membership), :id => nil, :class => 'checkbox' %>
			              <%= membership.user.name_or_email %>
			            </label>
		            </td>
		          </tr>
		        <% end %>
		      </tbody>
		    </table>
			<% end %>
	  </div>
	<% else %>
		<div class="blank_slate">
	    <%= image_tag 'empty_box.png', :style => 'width:125px;' %>
			<div class="message">
					<h2>There are no members on this team</h2>
					<p>
						Before you can assign this skill, you'll need some members to assign it to!
						Add some members from your account, and then return to this page to assign their skills.
					</p>
	      	<%= render :partial => 'shared/button_link', :locals => { :url => new_team_membership_path(@team), :text => 'Add the first member' } %>				
		</div>
	<% end %>
</div>