config/routes.rb
Worshipschedule::Application.routes.draw do

  resources :teams do
    member do
      get :assign
      put :assign_all, :to => 'teams#assign_all'
      put :remove_all, :to => 'teams#remove_all'
      get :admins
      put :admins, :to => 'teams#update_admins'
      get :slots
    end
    
    resources :availabilities, :only => [:update, :create]
    
    resources :events do
      member do
        put :slots, :to => 'events#slots'
      end
    end
    resources :slots, :only => [:update]
    
    resources :memberships do
      member do
        get :skillships, :to => 'memberships#skillships'
        put :skillships, :to => 'memberships#update_skillships'
      end
    end
    
    resources :skills  do
      member do
        get :skillships, :to => 'skills#skillships'
        put :skillships, :to => 'skills#update_skillships'
      end
    end
  end

  resources :accounts do
    member do
      get :admins
      put :admins, :to => 'accounts#update_admins'
      put :owner
    end
  end
  
  resources :users do
    member do
      put :memberships_for
    end
  end
  
  match "users/:id/send_reset", :to => 'users#send_reset', :as => 'users/send_reset', :only => 'post'
  
  resource :profile, :only => [:edit, :update] do
    get :forgot
    post :send_reset
  end

  match "profile/reset/:token", :to => 'profiles#reset', :as => 'profile/reset'
  match "profile/update_reset/:id", :to => 'profiles#update_reset', :as => 'profile/update_reset', :only => 'post'
  
  resources :sessions, :only => [:new, :create, :destroy]
  get 'sessions/accounts'
  post 'sessions/set_account'
  
  match 'signin' => 'sessions#new'
  match 'signout' => 'sessions#destroy'

  get "pages/home"
  
  root :to => "pages#home"

end

app/views/shared/_button_link.html.erb
<div class="big_button">
  <a href="<%= url %>">
    <span><%= text %></span>
  </a>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="error">
    <h3><%= pluralize(object.errors.count, 'error') %> kept this item from being saved</h3>
    <ol>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ol>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div id="header">
  
	<% if ['accounts', 'sessions'].include? controller.controller_name %>
  
    <%= render :partial => 'shared/status' %>
    <h1>
      <% unless current_account.nil? %>
        <%= current_account.name %></h1>
      <% else %>
        <%= APP_NAME %>
      <% end %>
    
  <% elsif ['teams', 'memberships', 'skills', 'events'].include? controller.controller_name %>
  
    <div class="include_backlink">
      <ul><li><%= link_to "&laquo; Back to teams".html_safe, current_user %></li></ul>
      <%= render :partial => 'shared/status', :locals => { :team => @team } %>
      <h1>
        <%= @team.name%>
        <span><%= current_account.name %></span>
      </h1>
    </div>
    
  <% else %>
  
    <%= render :partial => 'shared/status', :locals => { :team => @team } %>
    <h1><%= current_account.name %></h1>
    
  <% end %>
  
  <%= render 'shared/tabstrip' %>
</div>

app/views/shared/_show_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, :class => "flash #{key}") %>
<% end %> 

app/views/shared/_status.html.erb
<div class="status">
   <% if ['teams'].include?(controller.controller_name) && !['create', 'new'].include?(controller.action_name) %>
		<% if admin? || team_admin?(@team, current_user)%>
     	<%= link_to "Team settings", edit_team_path(@team), :class => 'settings' %>
		<% else %>
     	<%= current_user.name_or_email %>
		<% end %>
		
	<% elsif ['skills', 'events'].include?(controller.controller_name) %>
		<% if admin? || team_admin?(@team, current_user)%>
			<%= link_to "Team settings", edit_team_path(@team), :class => 'settings' %>
		<% else %>
     	<%= current_user.name_or_email %>			
		<% end %>
   <% else %>
     <%= current_user.name_or_email %>
   <% end %>

  | <%= link_to 'My info', edit_user_path(current_user) %>
  | <%= link_to 'Sign out', signout_path, :method => :delete %>
  | <a href="#">Help</a>
</div>

app/views/shared/_tabstrip.html.erb
<% if ['accounts'].include?(controller.controller_name) && ['index'].include?(controller.action_name) %>
  <ul class="tabs">
    <li><%= link_to 'Churches', sessions_accounts_path, :class => 'accounts' %></li>
    <li><%= link_to 'Sign out', signout_path, :method => :delete %></li>
  </ul>
  
<% elsif ['teams', 'memberships', 'skills', 'events'].include?(controller.controller_name) && !(['teams'].include?(controller.controller_name) && ['new', 'create'].include?(controller.action_name)) %>
  <ul class="tabs">
    <li><%= link_to "Overview", @team, :class => 'teams' %></li>
    <li><%= link_to "Skills", team_skills_path(@team), :class => 'skills' %></li>
    <li><%= link_to "Events", team_events_path(@team), :class => 'events' %></li>
    <li><%= link_to "Files", "/" %></li>
  </ul>
  <% if admin? %>
    <ul class="tabs admin">
      <li><%= link_to "People and permissions", team_memberships_path(params[:id]), :class => 'users' %></li>
      <li><%= link_to "Email", "/" %></li>
    </ul>
  <% end %>
  
<% else %>
  <ul class="tabs">
    <li><%= link_to 'Dashboard', current_user, :class => 'dashboard' %></li>
    <li><%= link_to 'Churches', sessions_accounts_path, :class => 'accounts' %></li>
    <li><a href="#">Events</a></li>
  </ul>
  <% if admin? %>
    <ul class="tabs admin">
      <li><%= link_to 'All people', users_path, :class => 'users' %></li>
      <% if current_account.owner == current_user %>
        <li><%= link_to 'Account', edit_account_path(current_account), :class => 'account' %></li>
      <% end %>
      <li><a href="#">Email</a></li>
    </ul>
  <% end %>
<% end %>