config/routes.rb
Worshipschedule::Application.routes.draw do

  resources :teams do
    member do
      get :assign
      put :assign_all, :to => 'teams#assign_all'
      put :remove_all, :to => 'teams#remove_all'
      get :admins
      put :admins, :to => 'teams#update_admins'
      get :slots
    end
    
    resources :availabilities, :only => [:update, :create]
    
    resources :events do
      member do
        put :slots, :to => 'events#slots'
      end
    end
    resources :slots, :only => [:update]
    
    resources :memberships do
      member do
        get :skillships, :to => 'memberships#skillships'
        put :skillships, :to => 'memberships#update_skillships'
      end
    end
    
    resources :skills  do
      member do
        get :skillships, :to => 'skills#skillships'
        put :skillships, :to => 'skills#update_skillships'
      end
    end
  end

  resources :accounts do
    member do
      get :admins
      put :admins, :to => 'accounts#update_admins'
      put :owner
    end
  end
  
  resources :users do
    member do
      put :memberships_for
    end
  end
  
  match "users/:id/send_reset", :to => 'users#send_reset', :as => 'users/send_reset', :only => 'post'
  
  resource :profile, :only => [:edit, :update] do
    get :forgot
    post :send_reset
  end

  match "profile/reset/:token", :to => 'profiles#reset', :as => 'profile/reset'
  match "profile/update_reset/:id", :to => 'profiles#update_reset', :as => 'profile/update_reset', :only => 'post'
  
  resources :sessions, :only => [:new, :create, :destroy]
  get 'sessions/accounts'
  post 'sessions/set_account'
  
  match 'signin' => 'sessions#new'
  match 'signout' => 'sessions#destroy'

  get "pages/home"
  
  root :to => "pages#home"

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :team
  has_many :slots, :dependent => :destroy
  has_many :availabilities, :dependent => :destroy
  has_many :memberships, :through => :availabilities
    
  attr_accessor :start_at_date, :start_at_time, :end_at_date, :end_at_time
  attr_accessible :team_id, :start_at_date, :start_at_time, :end_at_date, :end_at_time, :name, :description
  
  validates :name, :length => { :maximum => 100}
  validates :description, :length => { :maximum => 500 }
  
  validates_date :start_at_date, :allow_blank => false
  validates_time :start_at_time, :allow_blank => true
  
  validates_date :end_at_date, :allow_blank => true, :after => :start_at_date, :after_message => 'must be after starting date'
  validates_time :end_at_time, :allow_blank => true, :after => :start_at_time, :after_message => 'must be after starting time'
  
  before_save :set_start_at_end_at
  before_save do |event|
    event.name = 'Untitled event' if event.name.blank?
  end
  
  after_initialize :refresh_readable_attributes
  after_find :refresh_readable_attributes
  
  def when_range_text
    str = start_at_date.to_date.strftime("%A, %d %B")   
    if all_day?
      str << " - #{end_at_date.to_date.strftime("%A, %d %B")}" unless end_at_date.nil?
    else
      str << ", #{Time.parse(start_at_time).strftime("%l:%M%P").downcase.strip.chop}"
      str << " - #{Time.parse(end_at_time).strftime("%l:%M%P").downcase.strip.chop}" unless end_at_time.nil?
    end
    str
  end
  
  def all_day_text
    if all_day?
      unless end_at.nil?
        "Multi day"
      else
        "All day"
      end
    else
      Time.parse(start_at_time).strftime("%l:%M%P").downcase.chop
    end
  end
  
  private 
  
    def refresh_readable_attributes
      
      unless start_at.nil?
        if all_day?
          self.start_at_time = nil
          self.end_at_time = nil
          self.start_at_date = start_at.to_date.strftime("%Y-%m-%d").strip
          if end_at.nil?
            self.end_at_date = nil
          else
            self.end_at_date = end_at.to_date.strftime("%Y-%m-%d").strip
          end
        end
          
        if !all_day?
          self.start_at_date = start_at.to_date.strftime("%Y-%m-%d").strip
          self.start_at_time = start_at.to_time.strftime("%l:%M %P").strip
          self.end_at_date = nil
          if end_at.nil?
            self.end_at_time = nil
          else
            self.end_at_time = end_at.to_time.strftime("%l:%M %P").strip
          end
        end
      end  
    end
  
    def set_start_at_end_at
      
      if start_at_time.blank?
        
        # no start_at_time so ..        
        if end_at_date.blank?
          # its all_day, start_at_date only, disregard times
          self.all_day = true
          self.start_at = DateTime.new(DateTime.parse(start_at_date).year, DateTime.parse(start_at_date).month, DateTime.parse(start_at_date).day, 0, 0, 0, 0)        
          self.end_at = nil
        else
          # its all_day, start_at-date + end_at_date, disregard times 
          self.all_day = true
          self.start_at = DateTime.new(DateTime.parse(start_at_date).year, DateTime.parse(start_at_date).month, DateTime.parse(start_at_date).day, 0, 0, 0, 0) unless start_at_date.blank?        
          self.end_at = DateTime.new(DateTime.parse(end_at_date).year, DateTime.parse(end_at_date).month, DateTime.parse(end_at_date).day, 0, 0, 0, 0) unless start_at_date.blank?
        end
      end
      
      if !start_at_time.blank?  
        # has start_at_time so ..
        if end_at_time.blank? 
          # its not all_day, start_at_date + start_at_time, disregard end_at_time + end_at_date
          self.all_day = false
          self.start_at = DateTime.new(DateTime.parse(start_at_date).year, DateTime.parse(start_at_date).month, DateTime.parse(start_at_date).day, DateTime.parse(start_at_time).hour, DateTime.parse(start_at_time).min, 0, 0) unless start_at_date.blank?
          self.end_at = nil
        else
          # its not all_day, start_at_date = end_at_date, save times too
          self.all_day = false
          self.start_at = DateTime.new(DateTime.parse(start_at_date).year, DateTime.parse(start_at_date).month, DateTime.parse(start_at_date).day, DateTime.parse(start_at_time).hour, DateTime.parse(start_at_time).min, 0, 0) unless start_at_date.blank?
          self.end_at = DateTime.new(DateTime.parse(start_at_date).year, DateTime.parse(start_at_date).month, DateTime.parse(start_at_date).day, DateTime.parse(end_at_time).hour, DateTime.parse(end_at_time).min, 0, 0) unless start_at_date.blank?
        end
      end 
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter(:except => [:show, :index]) { require_account_or_team_admin(params[:team_id]) }
  before_filter { require_team_for_current_account(params[:team_id]) }
  before_filter(:except => [:new, :create, :index]) { require_event_for_current_team(params[:team_id], params[:id])}
  before_filter { require_team_member(params[:team_id]) }
  before_filter(:only => :slots) { require_skillships_for_current_team(params[:team_id], params[:add] ||= [], params[:remove] ||= []) }
  
  def slots
    @team = Team.find(params[:team_id])
    @event = Event.find(params[:id]) 

    if params[:add_slots] && (params[:add] ||= []).any?
      params[:add].each { |id| Slot.create(:event_id => @event.id, :skillship_id => id) unless id.blank? }
    elsif params[:remove_slots] && (params[:remove] ||= []).any?
      params[:remove].each { |id| Slot.where(:event_id => @event.id, :skillship_id => id).first.destroy unless id.blank? }
    end

    redirect_to slots_team_url(@team)
  end
  
  def show
    @team = Team.find(params[:team_id])
    @event = Event.find(params[:id])

    @sidebar_partial = 'events/sidebar/show'
    @title = 'Event details'
    render 'show'
  end
  
  def destroy
    @event = Event.find(params[:id])
    @event.delete
    redirect_to team_events_url(params[:team_id]), :flash => { :success => 'Your event was removed'}
  end
  
  def update
    @team = Team.find(params[:team_id])
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      flash[:success] = "The changes to the event were saved"
      redirect_to(team_events_url(@team))
    else
      @sidebar_partial = 'users/sidebar/placeholder'
      render 'edit'
    end    
  end
  
  def edit
    @team = Team.find(params[:team_id])
    @event = Event.find(params[:id])
    @title = 'Edit event'
    @sidebar_partial = 'events/sidebar/edit'
  end 
  
  def index
    @team = Team.find(params[:team_id])
    @events = @team.events
    @events.sort! { |a,b| b.start_at <=> a.start_at}
    @slots = Slot.find(
      :all,
      :joins => [:event, :skillship => [:skill, { :membership => :user }]],
      :conditions => ['users.id = ? AND memberships.team_id = ?', current_user.id, @team.id]
    )
    @slots.sort! { |a,b| b.event.start_at <=> a.event.start_at}
    
    @title = 'All events'
    @sidebar_partial = 'events/sidebar/index'
  end
  
  def create 
    @team = Team.find(params[:team_id])
    @event = @team.events.new(params[:event])
    if @event.save
      flash[:success] = 'The new event was successfully saved '
      redirect_to(team_events_url(@team))
    else
      @sidebar_partial = 'users/sidebar/placeholder'
      render 'new'
    end
  end
  
  def new
    @team = Team.find(params[:team_id])
    @event = @team.events.new(:start_at_date => Date.today.to_s)
    @title = "New event"
    @sidebar_partial = 'users/sidebar/placeholder'
  end
  
  private
  
    def require_skillships_for_current_team(team_id, add_ids, remove_ids)
      included = true
      team = Team.find(team_id)
    
      membership_ids = Skillship.find(add_ids + remove_ids).collect { |skillship| skillship.membership_id }
      membership_ids.each do |membership_id|
        unless team.membership_ids.include?(membership_id)
          included = false
        end
      end
    
      if !included
        redirect_to slots_team_url(team), :flash => { :error => "You do not have permission to modify one (or more) of the members you selected " }
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
  
  def user_slots_for(user, team)
    # return a two-dimensional array ..
    # => .[0] = event
    # => .[1] = comma-delim list of skills for the passed in membership for that event
    
    slots = Slot.find(
      :all,
      :joins => [:event, :skillship => [:skill,  :membership]],
      :conditions => ['memberships.user_id = ? AND memberships.team_id = ?', user.id, team.id]
    )  
    
    if slots.any?
      slots = slots.collect { |slot| [slot.event, slots.find_all { |sl| sl.event_id == slot.event_id }.map { |sl| sl.skillship.skill.name }.join(", ")] }
      slots.uniq!
    end
    slots ||= []
  end
  
  def slots_for(event)
    # return a two-dimensional array ..
    # => .[0] = user
    # => .[1] = comma-delim list of skills for the passed in event
    
    slots = Slot.find(
      :all,
      :joins => [:event, :skillship => { :membership => :user }],
      :conditions => ['events.id = ?', event.id],
      :order => 'CASE WHEN (LENGTH(last_name) = 0) THEN LOWER(email) ELSE LOWER(last_name) END'
    ) 
    
    if slots.any?
      slots = slots.collect { |slot| [slot.skillship.membership.user, slots.find_all { |sl| sl.skillship.membership_id == slot.skillship.membership_id }.map { |sl| sl.skillship.skill.name }.join(", ")]}
      slots.uniq!
    end
    slots ||= []
  end
end

app/views/events/_availability_chooser_for.html.erb
<% membership = user.memberships.where('team_id =?', team.id).first %>
<% availability = Availability.where('membership_id = ? AND event_id = ?', membership.id, event.id).first %>

<div class="availability_chooser">
	<% if availability.nil? %>
		<%= form_for 	:availability, :url => team_availabilities_path(team), :remote => true, :id => nil do |f| %>
			<%= f.hidden_field :event_id, :value => event.id, :id => nil %>
			<%= f.hidden_field :membership_id, :value => membership.id, :id => nil  %>
			<%= f.hidden_field :free, :value => true, :id => nil  %>
			<%= f.submit 'Available?', :id => nil %>
		<% end %>
		<%= form_for 	:availability, :url => team_availabilities_path(team), :remote => true, :id => nil do |f| %>
			<%= f.hidden_field :event_id, :value => event.id, :id => nil  %>
			<%= f.hidden_field :membership_id, :value => membership.id, :id => nil  %>
			<%= f.hidden_field :free, :value => false, :id => nil  %>
			<%= f.submit 'Not available?', :id => nil %>
		<% end %>												
	<% else %>											
		<% if availability.free? %>
			<%= form_for availability, :url => team_availability_path(team, availability), :remote => true, :id => nil do |f| %>
				<%= f.hidden_field :free, :value => true, :id => nil  %>
				<%= f.submit 'Available', :class => 'available selected', :id => nil %>													
			<%end %>
			<%= form_for availability, :url => team_availability_path(team, availability), :remote => true, :id => nil do |f| %>
				<%= f.hidden_field :free, :value => false, :id => nil  %>
				<%= f.submit 'Not available', :id => nil %>													
			<%end %>
		<% else %>
			<%= form_for availability, :url => team_availability_path(team, availability), :remote => true, :id => nil do |f| %>
				<%= f.hidden_field :free, :value => true, :id => nil  %>
				<%= f.submit 'Available', :id => nil %>													
			<%end %>
			<%= form_for availability, :url => team_availability_path(team, availability), :remote => true, :id => nil do |f| %>
				<%= f.hidden_field :free, :value => false, :id => nil  %>
				<%= f.submit 'Not available', :class => 'not_available selected', :id => nil %>													
			<%end %>
		<% end %>
	<% end %>
</div>

app/views/events/_fields.html.erb
<% content_for :head do %>
	<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css" type="text/css" rel="stylesheet" />
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>  
	<script type="text/javascript">
	
		var options = {dateFormat: 'yy-mm-dd'}
	
		function clear_date_picker(){
			$("table.time input").val('')
			$("div.end input").val('')
		}
		
		function set_date_picker(is_all_day, trigger){
			time_inputs = $("table.time")
			end_date_input = $("tr.to_date")
			to_from_labels = $("td.to_from_labels")
			

			if (is_all_day) {
				trigger.addClass('multi')
				trigger.text('Make this a one-day event')
				time_inputs.hide()
				end_date_input.show()
				to_from_labels.show()
			console.log("running set_date_picker ..")
			}
			else {
				trigger.removeClass('multi')
				trigger.text('Make this a multi-day event')
				time_inputs.show()
				end_date_input.hide()
				to_from_labels.hide()
			}
		}
    
    $(document).ready(function(){

			// arm the date-picker text fields ..
			$("#datepicker_start").datepicker(options)
			$("#datepicker_end").datepicker(options)
	
			// arm the date selector trigger ..
			$(".trigger a").click(function(){

				clear_date_picker()
				if ($(this).hasClass("multi")) { 
					set_date_picker(false, $(this))
				}
				else { 
					set_date_picker(true, $(this)) 
				}				
				return false
			})
			
    })
  </script>
<% end %>

<h3>Event name</h3>
<p class="block_intro">Provide a name for this event. </p>
<div class="block">
  <%= f.text_field :name %>
</div>
<h3>When?</h3>
<p class="block_intro">The start date and optional ending date. Start and end times are optional. </p>
<div class="block date">
		<table>
			<tbody>
				<tr>
					<td>
						<% if @event.all_day %>
							<% trigger_text = 'Make this a one-day event'%>
							<% end_at_display_style = ''%>
							<% time_field_display_style = 'display:none;'%>
							<% to_from_labels_display_style = '' %>
							<% trigger_class = 'multi' %>
						<% else %>
							<% trigger_text = 'Make this a multi-day event'%>
							<% end_at_display_style = 'display:none;'%>
							<% trigger_class = '' %>
							<% time_field_display_style = '' %>
							<% to_from_labels_display_style = 'display:none;' %>
						<% end %>
						<table>
							<tbody>
								<tr class="from_date">
									<td class="to_from_labels" style="<%= to_from_labels_display_style %>">From</td>
									<td>
										<%= f.text_field :start_at_date, :class => 'date_field	', :id => "datepicker_start", :readonly => "readonly" %>
									</td>
								</tr>
								<tr class="to_date" style="<%= end_at_display_style%>">
									<td class="to_from_labels" style="<%= to_from_labels_display_style %>">To</td>
									<td>
										<%= f.text_field :end_at_date, :class =>'date_field', :id => "datepicker_end", :readonly => 'readonly' %>
									</td>
								</tr>
								<tr>
									<td class="to_from_labels" style="<%= to_from_labels_display_style %>">&nbsp;</td>
									<td class="trigger">
										<a href="#" class="<%= trigger_class%>"><%= trigger_text %></a>
									</td>
								</tr>
							</tbody>
						</table>
					</td>
					<td style="vertical-align:top;">
						<table class="time" style="<%= time_field_display_style %>">
							<tbody>
								<tr>
									<td class="label">&nbsp;from&nbsp;</td>
									<td>
										<div><%= f.text_field :start_at_time, :class => 'time_field start_time' %></div>
										<div class="hint">ex. 9:30 am</div>
									</td>
									<td class="label">&nbsp;to&nbsp;</td>
									<td>
										<%= f.text_field :end_at_time, :class => 'time_field end_time' %>
									</td>
								</tr>
							</tbody>
						</table>
					</td>
				</tr>
			</tbody>
		</table>
</div>
<h3>Description</h3>
<p class="block_intro">Provide an optional description. </p>
<div class="block">
  <%= f.text_area :description, :cols => 50, :rows => 10 %>
</div>

app/views/events/_slots_for.html.erb
<ul>
	<% slots = slots_for event %>
	<% if slots.any? %>
		<% slots.each do |slot| %>
		<li>
		<%= gravatar_for(slot[0], { :size => 35, :default => :identicon  }) %>
		<div>
			<%= slot[0].name_or_email %>
			<br />
			<span>
				<%= slot[1] %>
			</span>
		</div>
		</li>
		<% end %>
	<% else %>
		<li class="blank_slate">No one has been scheduled or assigned to this event. </li>
	<% end %>
</ul>

app/views/events/edit.html.erb
<div class="content shadow">
  <div class="header">
    <h2>Edit an event for <%= @team.name %></h2>
  </div>
  <div class="form">
    <%= form_for @event, :url => { :action => 'update' } do |f| %>
      <%= render 'shared/errors', :object => @event %>
      <%= render 'fields', :f => f %>      
      <div class="footer">
        <%= f.submit "Save changes" %>
        or <%= link_to "Cancel", team_event_path(@team, @event), :class => 'cancel' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    
    $(document).ready(function(){
			$('.for_events form').live('ajax:beforeSend', function(evt, xhr, settings){
				var button = $(this).find('input:submit')
				$(button).attr('value', 'Saving ..')
			})
			
			$('.for_events form')
				.live('ajax:success', function(evt, data, status, xhr){
					var form = $(this)
					form.parents('div.availability_chooser').replaceWith(xhr.responseText)
				})
				.live('ajax:error', function(evt, xhr, status, error){
					var str				
					str = 'So sorry! ' + error + 'You could try refreshing the page, '
					str = str + 'but if this problem continues you may need to contact support. '
					alert(str)
				})			
    })
  </script>
<% end %>

<div class="content shadow">
  <div class="header">
	<% if admin? || team_admin?(@team, current_user) %>
		<div class="link_bar">
			<%= link_to 'New event', new_team_event_path(@team) %>
		</div>
	<% end %>
    <h2>All events for <%= @team.name %></h2>
  </div>
	<% if @events.any? %>
		<% today = Date.new %>
		<div class="listing for_events">
			<table>
				<% @events.first.start_at.to_date.downto(@events.last.start_at.to_date) do |date| %>
					<% events_start_at = @events.map { |e| e.start_at.to_date }%>
					<% if events_start_at.include?(date) %>
						<tr class="date">
							<td class="when" colspan="2">
								<% if date == Time.now.to_date %>
								<h2 class="today">
									<span>Today</span>
								</h2>
								<% else %>
								<h2>
									<span><%= date.strftime("%A, %d %B %Y") %></span>
								</h2>
								<% end %>
							</td>
							<td>&nbsp;</td>
						</tr>
					<% end %>
					<% @events.each do |event| %>
						<% if event.start_at.to_date == date %>
							<tr>
								<td class="what">
									<span class="event">Event</span>
									<div class="start_at"><%= event.all_day_text %></div>
								</td>
								<td class="item">
									<div><%= link_to event.name, team_event_path(@team, event) %></div>
									<% unless event.description.blank? %>
										<div class="desc"><%= event.description %></div>
									<% end %>
									<% if team_member? current_user, @team %>
										<%= render :partial => 'availability_chooser_for', :locals => { :user => current_user, :team => @team, :event => event } %>
									<% end %>											
								</td>
							</tr>
						<% end %>
					<% end %>
				<% end %>
			</table>
		</div>
	<% else %>
		<div class="blank_slate">
	    <%= image_tag 'empty_box.png', :style => 'width:125px;' %>
			<div class="message">
				<% if team_admin?(@team, current_user) || admin? %>
					<h2>Let's add the first event to this team! </h2>
					<p>
						You'll need some events before you can start scheduling your people.
						Once you do, you can add people to events by skill.
					</p>
	      	<%= render :partial => 'shared/button_link', :locals => { :url => new_team_event_path(@team), :text => 'Add the first event' } %>				
				<% elsif %>
					<h2>This team doesn't have any events! </h2>
					<p>
						A team administrator still needs to create some events for this team. 
					</p>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/events/new.html.erb
<% content_for :head do %>
	<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css" type="text/css" rel="stylesheet" />
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>  
	<script type="text/javascript">
		function clear_date_picker(){
			$("span.time input").val('')
			$("div.end input").val('')
		}
    
    $(document).ready(function(){
	
			// arm the datepickers ..
			options = {
				dateFormat: 'yy-mm-dd'
			}
			$("#datepicker_start").datepicker(options)
			$("#datepicker_end").datepicker(options)
	
			// show and hide the start/end date form fields..
			$(".trigger a").click(function(){
				trigger = $(this)
				time_inputs = $("table.time")
				end_date_input = $("div.end")
				
				clear_date_picker()
				
				if (trigger.hasClass("multi")) {
					trigger.removeClass('multi')
					trigger.text('Make this a multi-day event')
					time_inputs.show()
					end_date_input.hide()
				}
				else {
					trigger.addClass('multi')
					trigger.text('Make this a one-day event')
					time_inputs.hide()
					end_date_input.show()
				}
				
				return false
			})
    })
  </script>
<% end %>

<div class="content shadow">
  <div class="header">
    <h2>Add an event for <%= @team.name %></h2>
  </div>
  <div class="form">
    <%= form_for @event, :url => { :action => 'create' } do |f| %>
      <%= render 'shared/errors', :object => @event %>
      <%= render 'fields', :f => f %>      
      <div class="footer">
        <%= f.submit "Save changes" %>
        or <%= link_to "Cancel", team_events_path(@team), :class => 'cancel' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="content shadow">
  <div class="header">
		<% if team_admin?(@team, current_user) %>
			<div class="link_bar">
				<%= link_to 'New event', new_team_event_path(@team) %>
				|
				<%= link_to 'Edit', edit_team_event_path(@team, @event) %>
			</div>
		<% end %>
		<%= link_to "&laquo; All events".html_safe, team_events_path(@team), :class => 'back_link' %>
  </div>
	<div class="listing event">
		<h6><%= @event.when_range_text %></h6>
		<h2><%= @event.name %></h2>
		<p>
		<% if @event.description.blank? %>
			No description provided
		<% else %>
			<%= @event.description %>
		<% end %>
		</p>
	</div>
</div>